### ISSUE TITLE
Getos returning empty response causes TypeError

### ISSUE THREAD

**Issue by jakubzitny** [kevva/linux-distro#7]
Hi there, we've just had a case where a super custom version of Arch Linux caused `linux-distro` to throw a type error: `TypeError: Cannot read property 'dist' of null`.

I can see that there is already a PR for similar case in #6, I'll add one more check there and I hope you guys will merge it.

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/linux-distro/commit/a5b07cf043c2750e58ec538f2b7a7f927993ab7a.
